version: '3.4'

x-defaults: &defaults
  restart: unless-stopped
  image: sentry:9.0-onbuild
  depends_on:
    - redis
    - postgres
    - memcached
    - smtp
  env_file: .env
  volumes:
    - sentry-data:/var/lib/sentry/files
  networks:
    - manoj_assesment

services:
  smtp:
    restart: unless-stopped
    image: tianon/exim4
    networks:
    - manoj_assesment
    
  memcached:
    restart: unless-stopped
    image: memcached:1.5-alpine
    ports:
      - 11211
    networks:
    - manoj_assesment
  redis:
    restart: unless-stopped
    image: redis:3.2-alpine
    ports:
      - 6379
    networks:
    - manoj_assesment

  postgres:
    restart: unless-stopped
    image: postgres:9.5
    ports:
      - 5432:5432 
    volumes:
      - sentry-postgres:/var/lib/postgresql/data
    networks:
    - manoj_assesment
    env_file: .env_postgres

  web:
    <<: *defaults
    ports:
      - '9000:9000'

  cron:
    <<: *defaults
    command: run cron

  worker:
    <<: *defaults
    command: run worker


volumes:
    sentry-data:
      external: true
    sentry-postgres:
      external: true
networks:
  manoj_assesment:
    driver: bridge